#!/bin/bash
CNT=1
function checkErrors {
	if [ $? != 0 ]; then
	    >&2 echo "_STATUS_=RED Build failed"
	    exit 2
	else
		((CNT++))
		PROGRES=$((CNT * 14))
		>&1 echo "_STATUS_=GREEN $PROGRES "
	fi
}
cwd=$(pwd)

WORKSPACE=/Users/r00fi0/Work/mts/mts/MTS\ MB/mts-bank-patch
DESTINATION="$HOME"/Documents
# DESTINATION="$HOME"/Dropbox
# XC: rs.
PROVISIONING_PROFILE="$HOME"/Library/MobileDevice/Provisioning\ Profiles/2848f246-b7d5-4168-801d-8393efb92221.mobileprovision 
# XC:*
# PROVISIONING_PROFILE="$HOME"/Library/MobileDevice/Provisioning\ Profiles/c9d2d32e-c2d8-4312-817e-20ccf6098cb7.mobileprovision 
PROVISIONING_PROFILES="$HOME"/Library/MobileDevice/Provisioning\ Profiles
OUT_NAME=MobilePrototype2.ipa
SERVER_TYPE=FT
while getopts ":h:w:n:p:d:u:s:a:b:" opt; do
  case $opt in
  	h) HELP="Available arguments (-r project name) (-w path to project) (-n output ipa name) (-d destination for output ipa ) (-p path to PROVISIONING_PROFILE) (-u UUID of PROVISIONING_PROFILE)"
    ;;
  	w) WORKSPACE="$OPTARG"
    ;;
    n) OUT_NAME="$OPTARG"
    ;;
    p) PROVISIONING_PROFILE="$OPTARG"
    ;;
    u) PROVISIONING_PROFILE="$PROVISIONING_PROFILES"/"$OPTARG".mobileprovision
    ;;
    d) DESTINATION="$OPTARG"
    ;;
    s) SERVER_TYPE="$OPTARG"
    ;;
    a) ADD_PLATFORM="$OPTARG"
    ;;
    b) BUILD_PROJECT="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done
if [[ "$HELP" != "" ]]; then
	echo "$HELP"
else
	printf "Argument WORKSPACE is %s\n" "$WORKSPACE"
	printf "Argument OUT_NAME is %s\n" "$OUT_NAME"
	printf "Argument PROVISIONING_PROFILE is %s\n" "$PROVISIONING_PROFILE"
	printf "Argument DESTINATION is %s\n" "$DESTINATION"	
	printf "Argument SERVER_TYPE is %s\n" "$SERVER_TYPE"	
fi
cwd=/Users/r00fi0/Work/buildmachine
cp "$cwd"/"$SERVER_TYPE"/config.xml "$WORKSPACE"/
cp "$cwd"/"$SERVER_TYPE"/Config.js "$WORKSPACE"/www/js/
PROJECT_NAME="$(cat "$WORKSPACE"/config.xml | sed -n 's:.*<name>\(.*\)</name>.*:\1:p')"
LOG=/Users/r00fi0/Work/buildmachine/log
cd "$WORKSPACE"
# svn up
if [ "$ADD_PLATFORM" = true ]; then
	cordova platform remove ios > "$LOG"
	cordova platform add ios  >> "$LOG"
	checkErrors
fi

if [[ "$BUILD_PROJECT" = true ]]; then
	cordova build ios > "$LOG"
	checkErrors
fi

echo "$PROJECT_NAME"
WORKSPACE="$WORKSPACE"/platforms/ios

cp -r "$cwd"/"$PROJECT_NAME".xcodeproj "$WORKSPACE"
cp "$cwd"/"$SERVER_TYPE"/AppDelegate.m "$WORKSPACE"/"$PROJECT_NAME"/Classes/

BUILD="$WORKSPACE"/build
ARCHIVE_PATH="$BUILD"/"$PROJECT_NAME".xcarchive
IPA_PATH="$BUILD"/"$PROJECT_NAME".ipa

PLIST="$WORKSPACE"/"$PROJECT_NAME"/"$PROJECT_NAME"-Info.plist 
WORK_SPACE_FILE="$WORKSPACE"/"$PROJECT_NAME".xcodeproj/project.xcworkspace

APP_DIR_NAME="$BUILD"/Payload/"$PROJECT_NAME".app

echo "Building Workspace $WORKSPACE   file = $WORK_SPACE_FILE  scheme $PROJECT_NAME apath = $ARCHIVE_PATH  build = $BUILD plist $PLIST"

xcrun xcodebuild -workspace "$WORK_SPACE_FILE" -scheme "$PROJECT_NAME" -configuration Release clean archive -archivePath "$ARCHIVE_PATH" ENABLE_BITCODE=NO >> "$LOG"
checkErrors
xcrun xcodebuild -exportArchive -exportPath "$BUILD" -archivePath "$ARCHIVE_PATH" -exportOptionsPlist "$PLIST" ENABLE_BITCODE=NO > "$LOG"
checkErrors
rm -r "$BUILD"/Payload
unzip "$IPA_PATH" -d "$BUILD"/ >> "$LOG"
checkErrors
rm -r "$APP_DIR_NAME"/_CodeSignature/ "$APP_DIR_NAME"/CodeResources 2> /dev/null | true
cp  "$PROVISIONING_PROFILE" "$BUILD"/Payload/"$PROJECT_NAME".app/embedded.mobileprovision
codesign -f -s "iPhone Distribution: R-Style Softlab"  "$BUILD"/Payload/"$PROJECT_NAME".app/ >> "$LOG"
checkErrors
cd "$BUILD"

zip -qr "$OUT_NAME" Payload 
cp "$BUILD"/"$OUT_NAME" "$DESTINATION"
rm -r "$BUILD"/Payload "$ARCHIVE_PATH" "$IPA_PATH" "$BUILD"/"$OUT_NAME"
echo "_STATUS_=DONE ALL TASK DONE. BULD IS GREEN"
# 2

# rm -r MTS\ Bank.app/_CodeSignature/ MTS\ Bank.app/CodeResources 2> /dev/null | true

# codesign -f -s "iPhone Distribution: R-Style Softlab"  MTS\ Bank.app/

# xcrun xcodebuild -exportArchive -exportPath ~/Work/mts/mts/MTS\ MB/mts-bank-patch-ope/platforms/ios/build/ -archivePath "~/Work/mts/mts/MTS MB/mts-bank-patch-ope/platforms/ios/build/MTS Bank.xcarchive/" -exportOptionsPlist ~/Work/mts/mts/MTS\ MB/mts-bank-patch-ope/platforms/ios/MTS\ Bank/MTS\ Bank-Info.plist




# xcodebuild -schme "MTS Bank" -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="iPhone Distribution: R-Style Softlab" PROVISIONING_PROFILE="2848f246-b7d5-4168-801d-8393efb92221" 
# xcrun codesign -dv MTS\ Bank.app/

# git diff MTS\ Bank.app/ ~/Documents/MTS\ Bank\ 2016-05-27\ 18-36-48OPE/Payload/MTS\ Bank.app/