#!/bin/bash

cwd=$(pwd)
cwd="$HOME"/Work/buildmachine
CNT=1
WORKSPACE="$HOME"/Work/buildmachine/mts-bank-patch
DESTINATION="$HOME"/Documents
PROVISIONING_PROFILES="$HOME"/Library/MobileDevice/Provisioning\ Profiles
PROVISIONING_PROFILE="$PROVISIONING_PROFILES"/2848f246-b7d5-4168-801d-8393efb92221.mobileprovision
OUT_NAME=MobilePrototype2.ipa
SERVER_TYPE=FT
LOG="$HOME"/Work/buildmachine/log



while getopts ":h:w:n:d:u:s:a:b:e:" opt; do
  case $opt in
    h) HELP="Available arguments (-r project name) (-w path to project) (-n output ipa name) (-d destination for output ipa ) (-p path to PROVISIONING_PROFILE) (-u UUID of PROVISIONING_PROFILE)"
    ;;
    w) WORKSPACE="$OPTARG"
    ;;
    n) OUT_NAME="$OPTARG"
    ;;
    u) PROVISIONING_PROFILE="$PROVISIONING_PROFILES"/"$OPTARG".mobileprovision
    ;;
    d) DESTINATION="$OPTARG"
    ;;
    s) SERVER_TYPE="$OPTARG"
    ;;
    a) ADD_PLATFORM="$OPTARG"
    ;;
    b) BUILD_PROJECT="$OPTARG"
    ;;
    e) UPLOAD_TO_DROPBOX="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done
printf "$HELP"

BUILD="$WORKSPACE"/platforms/ios/build
IPA_PATH="$BUILD"/"$PROJECT_NAME".ipa

function begin {
    cp "$cwd"/"$SERVER_TYPE"/config.xml "$WORKSPACE"/
    cp "$cwd"/"$SERVER_TYPE"/Config.js "$WORKSPACE"/www/js/
    PROJECT_NAME="$(cat "$WORKSPACE"/config.xml | sed -n 's:.*<name>\(.*\)</name>.*:\1:p')"

    cd "$WORKSPACE"
    buildCordova
    WORKSPACE="$WORKSPACE"/platforms/ios

    cp -r "$cwd"/"$PROJECT_NAME".xcodeproj "$WORKSPACE"
    cp "$cwd"/"$SERVER_TYPE"/AppDelegate.m "$WORKSPACE"/"$PROJECT_NAME"/Classes/

    BUILD="$WORKSPACE"/build
    ARCHIVE_PATH="$BUILD"/"$PROJECT_NAME".xcarchive
    IPA_PATH="$BUILD"/"$PROJECT_NAME".ipa

    PLIST="$WORKSPACE"/"$PROJECT_NAME"/"$PROJECT_NAME"-Info.plist
    WORK_SPACE_FILE="$WORKSPACE"/"$PROJECT_NAME".xcodeproj/project.xcworkspace

    APP_DIR_NAME="$BUILD"/Payload/"$PROJECT_NAME".app

    echo "Building Workspace $WORKSPACE   file = $WORK_SPACE_FILE  scheme $PROJECT_NAME apath = $ARCHIVE_PATH  build = $BUILD plist $PLIST"

    archive
    postArchive
}
function archive {
    xcrun xcodebuild -workspace "$WORK_SPACE_FILE" -scheme "$PROJECT_NAME" -configuration Release clean archive -archivePath "$ARCHIVE_PATH" ENABLE_BITCODE=NO >> "$LOG"
    checkErrors
    xcrun xcodebuild -exportArchive -exportPath "$BUILD" -archivePath "$ARCHIVE_PATH" -exportOptionsPlist "$PLIST" ENABLE_BITCODE=NO >> "$LOG"
    checkErrors
    rm -r "$BUILD"/Payload
    unzip "$IPA_PATH" -d "$BUILD"/ > "$LOG"
    rm "$IPA_PATH"
    checkErrors
    rm -r "$APP_DIR_NAME"/_CodeSignature/ "$APP_DIR_NAME"/CodeResources 2> /dev/null | true
    cp  "$PROVISIONING_PROFILE" "$BUILD"/Payload/"$PROJECT_NAME".app/embedded.mobileprovision
    codesign -f -s "iPhone Distribution: R-Style Softlab"  "$BUILD"/Payload/"$PROJECT_NAME".app/ >> "$LOG"
    checkErrors
    cd "$BUILD"
    zip -qr "$OUT_NAME" Payload
}
function postArchive {

    if [ "$UPLOAD_TO_DROPBOX" = true ]; then
        cp "$BUILD"/"$OUT_NAME" "$DESTINATION"
    fi
    rm -r "$ARCHIVE_PATH"
    echo "_STATUS_=DONE ALL TASK DONE. BULD IS GREEN"
}

function buildCordova {
    svn up
    if [ "$ADD_PLATFORM" = true ]; then
      cordova platform remove ios > "$LOG"
      cordova platform add ios  > "$LOG"
    fi
    checkErrors
    if [[ "$BUILD_PROJECT" = true ]]; then
      cordova build ios > "$LOG"
    fi
    checkErrors
}

function checkErrors {
	if [ $? != 0 ]; then
	    >&2 echo "_STATUS_=RED Build failed"
	    exit 2
	else
		((CNT++))
		PROGRES=$((CNT * 14))
		>&1 echo "_STATUS_=GREEN $PROGRES "
	fi
}

begin

# 2

# rm -r MTS\ Bank.app/_CodeSignature/ MTS\ Bank.app/CodeResources 2> /dev/null | true

# codesign -f -s "iPhone Distribution: R-Style Softlab"  MTS\ Bank.app/

# xcrun xcodebuild -exportArchive -exportPath ~/Work/mts/mts/MTS\ MB/mts-bank-patch-ope/platforms/ios/build/ -archivePath "~/Work/mts/mts/MTS MB/mts-bank-patch-ope/platforms/ios/build/MTS Bank.xcarchive/" -exportOptionsPlist ~/Work/mts/mts/MTS\ MB/mts-bank-patch-ope/platforms/ios/MTS\ Bank/MTS\ Bank-Info.plist




# xcodebuild -schme "MTS Bank" -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="iPhone Distribution: R-Style Softlab" PROVISIONING_PROFILE="2848f246-b7d5-4168-801d-8393efb92221" 
# xcrun codesign -dv MTS\ Bank.app/

# git diff MTS\ Bank.app/ ~/Documents/MTS\ Bank\ 2016-05-27\ 18-36-48OPE/Payload/MTS\ Bank.app/